services:
  db:
    image: postgres:16
    container_name: countable-db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql
    ports:
        - "5432:5432"

volumes:
  db-data: {}