name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        working-directory: ./backend
        run: |
          chmod +x gradlew
          ./gradlew assemble
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        working-directory: ./backend
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/countable-springboot-backend .
      - name: Publish image to docker hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/countable-springboot-backend

  deploy:
    needs: build
    runs-on: [countable]
    steps:
      - name: Pull Image from docker hub
        run: docker pull ${{secrets.DOCKER_USERNAME}}/countable-springboot-backend:latest
      - name: Stop Docker Container
        run: docker rm -f countable-backend
      - name: Run Docker Container
        working-directory: ./backend
        run: |
          docker run --name countable-backend -p 8080:8080 \ 
          -e SPRING_DATASOURCE_URL=jdbc:postgresql://countable-postgres.cp82woymk3s7.ap-southeast-1.rds.amazonaws.com:5432/countabledb \
          -e SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver \
          -e SPRING_DATASOURCE_USERNAME=postgres \
          -e SPRING_DATASOURCE_PASSWORD=postgres \
          -e SPRING_JPA_HIBERNATE_DDL_AUTO=none \
          -e SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect \
          -e SPRING_SQL_INIT_MODE=always \
          -d ${{secrets.DOCKER_USERNAME}}/countable-springboot-backend:latest
